# Generated by Django 5.2.7 on 2025-10-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_chathistory_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='model_used',
            field=models.CharField(default='openai', max_length=20),
        ),
    ]
