# Generated by Django 5.2.7 on 2025-10-07 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_chathistory_model_used'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, null=True)),
                ('difficulty_level', models.CharField(default='normal', max_length=20)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Chat Caches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='difficulty_level',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pdf_images/')),
                ('page_number', models.IntegerField()),
                ('chunk_id', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_type', models.CharField(default='diagram', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='superadmin.uploadedbook')),
            ],
            options={
                'ordering': ['upload', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='PermanentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, null=True)),
                ('keywords', models.TextField(help_text='Keywords for quick search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permanent Memories',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['student', '-last_accessed'], name='students_pe_student_4a25b7_idx')],
            },
        ),
    ]
