# Generated by Django 4.2.11 on 2025-10-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_unittest_quizattempt_feedback_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 2023 Board Exam, Sample Paper 1', max_length=255)),
                ('standard', models.CharField(help_text='e.g., 10', max_length=10)),
                ('subject', models.CharField(help_text='e.g., Science, Mathematics', max_length=100)),
                ('exam_type', models.CharField(default='Board Exam', help_text='e.g., Board Exam, Sample Paper', max_length=100)),
                ('year', models.IntegerField(blank=True, help_text='Exam year', null=True)),
                ('pdf_file', models.FileField(upload_to='previous_year_papers/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_list', models.JSONField(blank=True, help_text='Extracted questions', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('total_papers_analyzed', models.IntegerField(default=0)),
                ('total_questions_analyzed', models.IntegerField(default=0)),
                ('chapter_importance', models.JSONField(default=dict, help_text='Chapter-wise importance scores')),
                ('topic_importance', models.JSONField(default=dict, help_text='Topic-wise importance scores')),
                ('question_frequency', models.JSONField(default=dict, help_text='Question type frequency')),
                ('priority_chapters', models.JSONField(default=list, help_text='Top priority chapters to study')),
                ('priority_topics', models.JSONField(default=list, help_text='Top priority topics')),
                ('study_strategy', models.JSONField(default=dict, help_text='Personalized study strategy')),
                ('estimated_study_hours', models.FloatField(default=0, help_text='Estimated hours needed')),
                ('analysis_completed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('papers', models.ManyToManyField(related_name='analyses', to='students.previousyearpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paper Analyses',
                'ordering': ['-analysis_completed_at'],
            },
        ),
    ]
