# Generated by Django 4.2.11 on 2025-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_previousyearpaper_paperanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Detailed AI-generated feedback', null=True),
        ),
        migrations.AddField(
            model_name='unittestanswer',
            name='awarded_marks',
            field=models.FloatField(default=0, help_text='Total marks awarded for this answer'),
        ),
        migrations.AddField(
            model_name='unittestanswer',
            name='evaluation_type',
            field=models.CharField(default='ai', help_text='exact, ai, or heuristic', max_length=20),
        ),
        migrations.AlterField(
            model_name='unittestanswer',
            name='content_score',
            field=models.FloatField(default=0, help_text='Content accuracy (0-1)'),
        ),
        migrations.AlterField(
            model_name='unittestanswer',
            name='grammar_score',
            field=models.FloatField(default=0, help_text='Grammar and language quality (0-1)'),
        ),
    ]
