# Generated by Django 4.2.11 on 2025-10-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_unittestanswer_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcache',
            name='has_rag_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatcache',
            name='is_invalidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatcache',
            name='negative_feedback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatcache',
            name='quality_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='chatcache',
            name='rag_relevance',
            field=models.FloatField(default=0.0),
        ),
    ]
