# Generated by Django 4.2.11 on 2025-11-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_chatcache_has_rag_context_chatcache_is_invalidated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('free', 'Free Conversation'), ('topic', 'Topic-Based Discussion'), ('presentation', 'Presentation Practice'), ('interview', 'Interview Simulation')], default='free', max_length=50)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('exchange_count', models.IntegerField(default=0, help_text='Number of back-and-forth exchanges')),
                ('word_count', models.IntegerField(default=0, help_text='Total words spoken by student')),
                ('conversation_data', models.JSONField(help_text='Full conversation history with timestamps')),
                ('overall_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('fluency_score', models.IntegerField(default=0)),
                ('vocabulary_score', models.IntegerField(default=0)),
                ('pronunciation_score', models.IntegerField(default=0)),
                ('coherence_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('grammar_errors', models.JSONField(default=list, help_text='List of grammar errors with corrections')),
                ('filler_words', models.JSONField(default=list, help_text='Filler words count (um, like, etc.)')),
                ('speaking_pace', models.JSONField(default=dict, help_text='Words per minute analysis')),
                ('strengths', models.JSONField(default=list, help_text='Identified strengths')),
                ('improvements', models.JSONField(default=list, help_text='Areas for improvement')),
                ('suggestions', models.JSONField(default=list, help_text='Detailed improvement suggestions with examples')),
                ('vocabulary_enhancement', models.JSONField(default=list, help_text='Vocabulary suggestions (basic → advanced)')),
                ('best_exchanges', models.JSONField(default=list, help_text='Best conversation exchanges')),
                ('needs_work', models.JSONField(default=list, help_text='Exchanges that need improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speaking Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='students_sp_student_370171_idx')],
            },
        ),
    ]
